import type { Metadata } from "next"
import "./globals.css"
import { GlobalContextProvider } from "./context/GlobalContext"
import { Providers } from "./providers"
import PWARegister from "./PWARegister"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
        <GlobalContextProvider>
          <Providers>
            <PWARegister /> {/* 👈 burada */}
            {children}
          </Providers>
        </GlobalContextProvider>
      </body>
    </html>
  )
}
